# Welcome to Jekyll!

# Website settings
title: Romain Vial
description: Personal webpage of Romain Vial, AI enthusiast!
keywords: github, gh-pages, Romain, Romain Vial, Deep Learning, Machine Learning
baseurl: # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://romainvial.github.io  # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Romain Vial # Be used at blog posts' author.
  first_name: Romain  # Be used at index page about me section.
  last_name: Vial  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: RomainVial  # Leave blank if you don't have now
  linkedin_id: vialromain # Leave blank if you don't have now
  facebook_username: # Leave blank if you don't have now
  twitter_username: # Leave blank if you don't have now
  angellist_username: romain-vial # Leave blank if you don't have now
  email: contact@romainvial.xyz # Leave blank if you don't have now
  rss: # Leave blank if you don't want a link to rss feed
  cv: # A online CV can be printed as PDF, leave blank if you don't have now
  desc: |
          Hi!

          My name is Romain Vial. I am a french Master Student at [MINES ParisTech](http://www.mines-paristech.eu/)
          pursuing a M.Sc. in Applied Probabilities.

          I am also enrolled in a double degree with [ENS Paris Saclay](http://www.ens-cachan.fr/en)
          in the [MVA Master programme](http://math.ens-paris-saclay.fr/version-francaise/formations/master-mva/)
          focusing on Machine Learning and Computer Vision.

          From July 2016 to September 2017, I took a gap year and had the chance to complete two very interesting
          internships. I first went to Singapore at [Institute for Infocomm Research](http://www.i2r.a-star.edu.sg/) where
          I worked on activity recognition in videos. Then, I continued in Heidelberg, Germany at
          [NEC Laboratories Europe](http://uk.nec.com/en_GB/emea/about/neclab_eu/index.html?) where I worked on
          Natural Language Processing and Deep Learning for aspect-based sentiment analysis. Both internships led to
          publications in machine learning and/or computer vision conferences.

          **I am currently looking for my final year internship beginning in April 2018. I am very interested in all
          the areas of Artificial Intelligence and Deep Learning in both research and production environments. Feel
          free to contact me!**

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-104132440-1
## google optimize
go:
  id:

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
